//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipBot_BL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipDb")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
            set {
                this["Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordToken {
            get {
                return ((string)(this["DiscordToken"]));
            }
            set {
                this["DiscordToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("457228636303654912")]
        public ulong PriceCheckChannel {
            get {
                return ((ulong)(this["PriceCheckChannel"]));
            }
            set {
                this["PriceCheckChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/21/2018 20:00:00")]
        public global::System.DateTime NextRelease {
            get {
                return ((global::System.DateTime)(this["NextRelease"]));
            }
            set {
                this["NextRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("457229141033484288")]
        public ulong TipBotChannel {
            get {
                return ((ulong)(this["TipBotChannel"]));
            }
            set {
                this["TipBotChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("459672024265261107")]
        public ulong FantasyChannel {
            get {
                return ((ulong)(this["FantasyChannel"]));
            }
            set {
                this["FantasyChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("372707284289060865")]
        public ulong GuildId {
            get {
                return ((ulong)(this["GuildId"]));
            }
            set {
                this["GuildId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QT_IP {
            get {
                return ((string)(this["QT_IP"]));
            }
            set {
                this["QT_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QT_Username {
            get {
                return ((string)(this["QT_Username"]));
            }
            set {
                this["QT_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QT_Password {
            get {
                return ((string)(this["QT_Password"]));
            }
            set {
                this["QT_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GRS")]
        public string BaseCurrency {
            get {
                return ((string)(this["BaseCurrency"]));
            }
            set {
                this["BaseCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://chainz.cryptoid.info/grs/tx.dws?")]
        public string ExplorerPrefix {
            get {
                return ((string)(this["ExplorerPrefix"]));
            }
            set {
                this["ExplorerPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".htm")]
        public string ExplorerSuffix {
            get {
                return ((string)(this["ExplorerSuffix"]));
            }
            set {
                this["ExplorerSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help support the developer funds, by donating or mining to FWN1qdiRrymSR6jbpbanLY" +
            "qZpjkEaZouHN")]
        public string FooterText {
            get {
                return ((string)(this["FooterText"]));
            }
            set {
                this["FooterText"] = value;
            }
        }
    }
}
